version: '3.1'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8080:8080
      - 50000:50000
    container_name: my_jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: animal_worlds
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
volumes:
  jenkins_home:
  postgres_data:
