version: '3.1'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8080:8080
      - 50000:50000
    container_name: my_jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
